apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  APP_ENV: "production"
  LOG_LEVEL: "debug"
  MAX_CONNECTIONS: "100"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1_container1
    image: nginx
    command: ["bin/bash","-c","while true; do echo $APP_ENV; sleep 20; done"]
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: configmap1
          key: APP_ENV