apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1_container1
    image: nginx
    volumeMounts:
    - name: pod1_container1_volume1
      mountPath: "/data"
    ports:
    - containerPort: 80
  volumes:
  - name: pod1_container1_volume1
    emptyDir:
      medium: "Memory"   #stores data in RAM instead of disk(emptyDir: {})
    