apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myApp
spec:
  containers:
  - name: container1(nginx)
    image: nginx
    ports:
      - containerPort: 80
        name: pod1-container1(nginx)

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: myApp
  ports:
  - name: port1
    protocol: TCP
    port: 80
    targetPort: pod1-container1(nginx)  