apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    deployment: deployment1
spec:
  replicas: 3
  selector:
    matchLables:
      app: deployment1_app
  template:
    metadata:
      labels:
        app: deployment1_app
    spec:
      containers:
      - name: container1
        image: nginx
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1