apiVersion: v1
kind: Pod
metadata:
  name: pod
  annotations:
    description: this is demo of pod
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo m1; sleep 10; done"]
    env:
      name: myname
      value: sagar
  - name: container2
    image: nginx
    ports:
    - containerPort: 80